import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState, useEffect } from 'react';

export default function Home() {
  const [success, setSuccess] = useState(false);
  useEffect(() => {
    if ( window.location.search.includes('success=true') ) {
      setSuccess(true);
    }
  }, []);
  <script src="https://platform.linkedin.com/badges/js/profile.js" async defer type="text/javascript"></script>
  return (
    <div className={styles.container}>
      <Head>
        <title>Daddy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to my page, by <a href="https://youtu.be/4fsPFhmbwFY">daddy!</a>
        </h1>
        {success && (
          <p style={{ color: 'green'}}>
            Successfully submitted form!
          </p>
        )}

        {/* <p className={styles.description}>
          Get started using this form: {' '}
        </p> */}
        <div className={styles.grid}>
          <div className={styles.card}>
            <form name="contact" method="POST" data-netlify="true" action="/?success=true">
            <input type="hidden" name="contact" value="contact" />

              <p>
                <label htmlFor="name">Name</label>
                <input type="text" id="name" name="name" />
              </p>
              <p>
                <label htmlFor="email">Email</label>
                <input type="text" id="email" name="email" />
              </p>
              <p>
                <label htmlFor="message">Message</label>
                <textarea id="message" name="message"></textarea>
              </p>
              <p>
                <button type="submit">Send</button>
              </p>
            </form>
          </div>              
        </div>

        <iframe>
        <div class="badge-base LI-profile-badge" data-locale="en_US" data-size="medium" data-theme="dark" data-type="HORIZONTAL" data-vanity="sherwin1" data-version="v1"><a class="badge-base__link LI-simple-link" href="https://www.linkedin.com/in/sherwin1?trk=profile-badge">🇺🇸 Sherwin M.</a></div>

        </iframe>
          
      </main>
      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}
